### ISSUE TITLE
Mention mpl-scatter-density in large data section?

### ISSUE THREAD

**Issue by astrofrog** [pyviz/website#42]
The [mpl-scatter-density](https://github.com/astrofrog/mpl-scatter-density) is a lightweight package that makes it possible to show large (up to ~10^9 points) datasets with Matplotlib. It might be worth mentioning it in the 'Large-data rendering' section but the issue is that that section specifically mentions 'server-side' rendering. Can we relax this wording to allow tools like mpl-scatter-density to be mentioned?

**Comment by jbednar** [comment]
Sure, sounds good!  Please make a PR to add it and to change the description as needed!
