### ISSUE TITLE
How to fix missing license?

### ISSUE THREAD

**Issue by birdsarah** [pyviz/website#44]
chartify has an Apache license: https://github.com/spotify/chartify/blob/master/ but it's not showing up on the tools.html page

![Screenshot from 2019-08-22 09-42-07](https://user-images.githubusercontent.com/1796208/63533197-28938700-c4c1-11e9-8234-5470039222e7.png)

Happy to make a pr with a little guidance.

**Comment by jbednar** [comment]
I hope @jsignell can help with that; I'm not sure how it's finding the license file and thus how it goes wrong as it does here and for several other libraries.  May be the same issue as https://github.com/pyviz/website/pull/41 .

**Comment by jsignell** [comment]
Right chartify needs to declare that in a way that pypi can read. I assume that happens in the setup.py. I'll open up an issue over there.

**Comment by jbednar** [comment]
Same for all the other ones with missing licenses?

**Comment by jsignell** [comment]
yep

**Comment by jbednar** [comment]
Ok, makes sense.  I guess we can have some boilerplate text for an issue to file on all those repos:

> Hi, I notice that your setup.py file doesn't declare the license used for this project.  Declaring it will help pypi.org display information about each project consistently, and it's also used in sites like https://pyviz.org/tools.html, which reads that information and summarizes it across projects. Is there any chance the setup.py file can be edited to include that information?

Or I guess we could make a PR with similar wording, which might have a greater likelihood of actually making it happen...
