### ISSUE TITLE
All Panel gallery examples currently broken

### ISSUE THREAD

**Issue by chrish42** [pyviz/website#47]
Hello. Not sure if this is the right place for this, but all the Panel gallery examples are currently broken. The interactive example at the center of the webpage only displays a "sad notebook" graphic, and trying the MyBinder ("Live app URL") link gives a "starting notebook" message, without seeming to make progress.

Here's an example URL: https://panel.pyviz.org/gallery/demos/gapminder.html#gallery-gapminder

(Installing some monitoring to learn about these problems not from GitHub issues might also be a good idea...)

**Comment by jbednar** [comment]
Sorry for the confusion!  We're currently working through some security certificate issues and taking the opportunity (while it's down already!) to do an upgrade of our server.  We're on it!

**Comment by chrish42** [comment]
No problem. Sorry for the GitHub noise, then. A little banner saying that it's done for maintenance and giving an approximate time back up would be really nice in the future, if possible. Otherwise it's just kinda hard to tell the difference between "down for maintenance, back up soon" and "it's been broken for a while, nobody notified the devs and they don't know". :-D Looking forward to giving the gallery a spin when it's back up!

**Comment by jbednar** [comment]
Unfortunately the whole server is down, so we can't even do that!
